package main

import (
	"github.com/gin-gonic/gin"
	"github.com/slycreator/shop-for-me/config"
	"github.com/slycreator/shop-for-me/controllers/Auth"
	"github.com/slycreator/shop-for-me/repository"
	"github.com/slycreator/shop-for-me/service"
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"
	_ "github.com/swaggo/gin-swagger/example/basic/docs" // docs is generated by Swag CLI, you have to import it.
	"gorm.io/gorm"
)

var (
	db             *gorm.DB                  = config.OpenDatabaseConnection()

	authRepository repository.AuthRepository = repository.NewAuthRepository(db)
	authService    service.AuthService       = service.NewAuthService(authRepository)
	jwtService     service.JWTService        = service.NewJWTService()
	authController Auth.AuthController       = Auth.NewAuthController(authService, jwtService)
)

// @title Swagger Example API
// @version 1.0
// @description This is a sample server Petstore server.
// @termsOfService http://swagger.io/terms/

// @contact.name API Support
// @contact.url http://www.swagger.io/support
// @contact.email support@swagger.io

// @license.name Apache 2.0
// @license.url http://www.apache.org/licenses/LICENSE-2.0.html

// @host petstore.swagger.io
// @BasePath /v2
func main() {
	r := gin.Default()

	url := ginSwagger.URL("http://localhost:2021/swagger/doc.json") // The url pointing to API definition
	r.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler, url))

	router := r.Group("v1/api")
	guestRoute := router.Group("/")
	{
		guestRoute.POST("/register", authController.Register)
		guestRoute.POST("/login", authController.Login)
		guestRoute.POST("/password/email", authController.VerifyNumber)
		guestRoute.POST("/password/check_token", authController.VerifyNumber)
		guestRoute.POST("/password/change_password", authController.ForgetPassword)
	}
		//Add a middleware to this route
		authRoute := router.Group("/")
		{
			authRoute.POST("/logout",authController.Register)
			authRoute.POST("/update_password",authController.Register)

			profileRoute := router.Group("/profile")
			{
				profileRoute.GET("/show",authController.Register)
				profileRoute.POST("/update",authController.Register)
				profileRoute.POST("/report",authController.Register)
				profileRoute.POST("/item_sent",authController.Register)
			}

			senderRoute := router.Group("/sender")
			{
				senderRoute.GET("/send",authController.Register)
				senderRoute.POST("/send_later",authController.Register)
				senderRoute.POST("/draft_shopping_list",authController.Register)


				offerRoute := senderRoute.Group("/offer")
				{
					offerRoute.POST("/create",authController.Register)
					SingleOfferRoute := offerRoute.Group("/{offer}")
					{
						SingleOfferRoute.POST("/", authController.Register)
						SingleOfferRoute.POST("/accept", authController.Register)
						SingleOfferRoute.POST("/decline", authController.Register)
					}
				}

				shoppingListroute := senderRoute.Group("/shopping_lists/{shopping_list}")
				{
					shoppingListroute.GET("/delete",authController.Register)
					shoppingListroute.POST("/accept_grocery_as_deliver",authController.Register)
					shoppingListroute.POST("/reject_grocery_as_deliver",authController.Register)
					shoppingListroute.POST("/rate_shopper",authController.Register)
				}

				trackRoute := senderRoute.Group("/track")
				{
					trackRoute.GET("/",authController.Register)
					trackRoute.POST("/{track}",authController.Register)
				}

			}
		}


	r.Run(":2021")
}

//nodemon --exec go run main.go --signal SIGTERM